<!DOCTYPE html>
<html lang="en">
<title>Home | Check what new information today</title>

<?php

require_once ('inc/header.phtml');

?>


<!-- Header
================================================= -->

<!--Header End-->

<div id="page-contents">
    <div class="container">
        <div class="row">

            <!-- Newsfeed Common Side Bar Left.
            ================================================= -->
            <div class="col-md-3 static">
                <div class="profile-card">
                    <img src="images/users/avatardefault.jpg" alt="user" class="profile-photo" />
                    <h5><a href="timeline.html" class="text-white">Anonymous</a></h5>
                    <a href="#" class="text-white"><i class="ion ion-android-person-add"></i> 0 Answer </a>
                </div><!--profile card ends-->
                <ul class="nav-news-feed">
                    <li><i class="icon ion-ios-paper"></i><div><a href="newsfeed.html">Books</a></div></li>
                    <li><i class="icon ion-ios-people"></i><div><a href="newsfeed-people-nearby.html">Technology</a></div></li>
                    <li><i class="icon ion-ios-people-outline"></i><div><a href="newsfeed-friends.html">Science</a></div></li>
                    <li><i class="icon ion-chatboxes"></i><div><a href="newsfeed-messages.html">Language</a></div></li>
                    <li><i class="icon ion-images"></i><div><a href="newsfeed-images.html">Health</a></div></li>
                    <li><i class="icon ion-ios-videocam"></i><div><a href="newsfeed-videos.html">Movies</a></div></li>
                </ul>
            </div>
            <div class="col-md-7">

                <!-- Post Create Box
                ================================================= -->
                <div class="create-post">
                    <div class="">
                        <div class="">
                            <a class=" btn btn-primary "  href="index.php?action=addPost" >+ New topic </a>






                        </div>

                        <!--<div class="col-md-5 col-sm-5">
                            <div class="tools">
                                <ul class="publishing-tools list-inline">
                                    <li><a href="#"><i class="ion-compose"></i></a></li>
                                    <li><a href="#"><i class="ion-images"></i></a></li>

                                </ul>
                                <button class="btn btn-primary pull-right">Publish</button>
                            </div>
                        </div>-->

                    </div>
                </div><!-- Post Create Box End-->

                <!-- Post Content
                ================================================= -->
                <?php
                foreach ( $dataUser as $value){
                    ?>
                <div class="post-content">
                    <!--<img src="../images/post-images/1.jpg" alt="post-image" class="img-responsive post-image" />-->
                    <h3><a href="#" class="profile-link">  <?php
                               echo $value->header;
                            ?>  </a> </h3>
                    <div class="post-container">
                        <img src="<?php  echo ($value->Infor_User[0]->Avatar); ?>" alt="user" class="profile-photo-md pull-left" />
                        <div class="post-detail">

                            <div class="user-info">
                                <h5><a href="timeline.html" class="profile-link"><?php  echo ($value->Infor_User[0]->Name); ?></a> <span class="following"><?php  echo $value->categories;  ?></span></h5>

                                <p class="text-muted"><?php echo  ($value->date_created); ?></p>
                            </div>

                            <div class="reaction">
                                <a class="btn text-green"><i class="icon ion-thumbsup"></i><?php  echo $value->like;  ?></a>
                                <a class="btn text-red"><i class="fa fa-thumbs-down"></i> <?php  echo $value->unlike; ?></a>
                            </div>
                            <div class="line-divider"></div>
                            <div class="">
                                <?php
                                for ($x = 0; $x < count($value->Tags); $x++) { ?>
                                <a href="#"  class="bts default" ><?php  echo $value->Tags[$x]; ?></a>
                                    <?php
                                }
                                ?>

                            </div>

                        </div>
                    </div>
                </div>
                <?php
                }
                ?>
            </div>

            <!-- Newsfeed Common Side Bar Right
            ================================================= -->
            <div class="col-md-2 static">
                <div class="suggestions" id="sticky-sidebar">
                    <h4 class="grey">Member Of Month</h4>
                    <div class="follow-user">
                        <img src="images/users/user-11.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Cris Haris</a></h5>
                            <a  class="text-green">0 Answers </a>
                        </div>
                    </div>
                    <div class="follow-user">
                        <img src="images/users/user-12.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Cris Haris</a></h5>
                            <a href="#" class="text-green">Add friend</a>
                        </div>
                    </div>
                    <div class="follow-user">
                        <img src="images/users/user-13.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Brian Walton</a></h5>
                            <a href="#" class="text-green">Add friend</a>
                        </div>
                    </div>
                    <div class="follow-user">
                        <img src="images/users/user-14.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Olivia Steward</a></h5>
                            <a href="#" class="text-green">Add friend</a>
                        </div>
                    </div>
                    <div class="follow-user">
                        <img src="images/users/user-15.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Sophia Page</a></h5>
                            <a href="#" class="text-green">Add friend</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Footer
================================================= -->
<?php

require_once 'inc/footer.phtml';


?>


</body>
</html>
